openapi: 3.0.1
info:
  title: Newfine API
  description: api.newfine.tk
  version: 0.0.1
servers:
- url: https://localhost:8080
tags: []
paths:
  /make/study:
    post:
      tags:
      - make
      operationId: 관리자 자습 생성
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/make-study-493007013'
            examples:
              관리자 자습 생성:
                value: "{\"startTime\":\"2020-09-23T18:34:24\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/make-study486549215'
              examples:
                관리자 자습 생성:
                  value: "{\"study_id\":1,\"url\":\"https://eb.newfine.tk/study.html?idx=1\"\
                    ,\"start_time\":[2020,9,23,18,34,24]}"
components:
  schemas:
    make-study-493007013:
      type: object
      properties:
        startTime:
          type: string
          description: 자습시작시간
    make-study486549215:
      type: object
